theme: jekyll-theme-hacker
titulo: Bienvenidos a Smart Parking 4u!

TSU Software, Materia: Programacion, Clave 50086, Semestre 17-P
Avance de proyecto final: Presentacion y avances.


Integrantes del equipo:

Hernandez Martinez Joaquin
Nava Rojas Edgardo
Mario Morales Sánchez


Motivacion del proyecto:


En la ciudad de Mexico los espacios de estacionamiento son cada vez más escasos. Encontramos en los estacionamientos publicos de pequeño y mediano tamaño, ciertos problemas con la administracion, los cobros pueden no ser tan exactos si no se tiene un sistema automatizado para llevar el control, a raíz de esto, no se tendrá una cifra real de las ganancias y podría facilitar el hecho de que sufran robos por parte de los mismos empleados.


Descripción de su solucion de software


Nuestra solucion registrara los movimientos de entrada y salida de vehiculo. Administrara la actividad de los pensionados. De este modo el administrador tiene la seguridad de que todas las actividades son registradas, eliminando la posibilidad de fraudes. 
Entre los beneficios estan; control exacto del acceso y pago de los vehiculos que ingresan al estacionamiento, control de acceso y administracion de vehiculos pensionados, reduccion de las perdidas por malos manejos en el cobro del servicio.


Asi mismo la solucion podra indicarle al usuario que lugar del estacionamiento se
encuentra su vehículo, facilitándole su ubicación.


Dirección repositorio


Repositorio: .
github.com/joaquinhmtz/joaquinhmtz.github.io
Publicación:
github.com/joaquinhmtz/joaquinhmtz.github.io/blob/master/ind
ex.html


Avances del proyecto


El programa tendrá 5 módulos que son pilares de la operación:
1. Pensionados
2. Acceso
3. Caja

Descripción módulos:


1. Pensionados
Registro de vehículos pensionados
Fecha de contratación del servicio y término
Nombre del propietario
Tipo de pensión
Cajón designado
Captura de placas


2. Acceso
Check in clientes
Captura de placas, hora y folio del ticket, lugar
Calcula tiempo y monto exacto del servicio
Indica qué lugar está desocupado


3. Caja
Lleva registro de las transacciones
Ingresa y retira dinero
Cortes al final del día


